services:
  cluster_a_master:
    container_name: cluster_a_master
    build: ./cluster_master
    networks:
      - distributed_network
    command: ["python3", "/app/master.py"]

  node_a1:
    container_name: node_a1
    build: ./node
    networks:
      - distributed_network
    command: ["python3", "/app/node.py"]

networks:
  distributed_network:
    driver: bridge
