services:
  # Cluster A
  cluster_a_master:
    container_name: cluster_a_master
    build: .
    ports:
      - "5001:5000"  # Expose different ports for each cluster
    networks:
      - cluster_a

  cluster_a_node_1:
    container_name: cluster_a_node_1
    build: .
    networks:
      - cluster_a

  cluster_a_node_2:
    container_name: cluster_a_node_2
    build: .
    networks:
      - cluster_a

  cluster_a_node_3:
    container_name: cluster_a_node_3
    build: .
    networks:
      - cluster_a

  cluster_a_node_4:
    container_name: cluster_a_node_4
    build: .
    networks:
      - cluster_a

  cluster_a_node_5:
    container_name: cluster_a_node_5
    build: .
    networks:
      - cluster_a

  cluster_a_node_6:
    container_name: cluster_a_node_6
    build: .
    networks:
      - cluster_a

  cluster_a_node_7:
    container_name: cluster_a_node_7
    build: .
    networks:
      - cluster_a

  # Cluster B
  cluster_b_master:
    container_name: cluster_b_master
    build: .
    ports:
      - "5002:5000"  # Different port for cluster B
    networks:
      - cluster_b

  cluster_b_node_1:
    container_name: cluster_b_node_1
    build: .
    networks:
      - cluster_b

  cluster_b_node_2:
    container_name: cluster_b_node_2
    build: .
    networks:
      - cluster_b

  cluster_b_node_3:
    container_name: cluster_b_node_3
    build: .
    networks:
      - cluster_b

  cluster_b_node_4:
    container_name: cluster_b_node_4
    build: .
    networks:
      - cluster_b

  cluster_b_node_5:
    container_name: cluster_b_node_5
    build: .
    networks:
      - cluster_b

  cluster_b_node_6:
    container_name: cluster_b_node_6
    build: .
    networks:
      - cluster_b

  cluster_b_node_7:
    container_name: cluster_b_node_7
    build: .
    networks:
      - cluster_b

networks:
  cluster_a:
  cluster_b:
